name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create asset
        run: zip ../pitchprint.ocmod.zip 3.0-ocmod/* -r 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "CHANGELOG.txt"
          name: "PitchPrint - OpenCart 3.x OCMOD - ${{ github.ref_name }}"
          files: "../pitchprint.ocmod.zip"